id: breastcancerspec
canonical: http://breastcancerspec.org
name: BreastCancerSpec
title: "Breast Cancer Specification"
description: "FHIR Implementation Guide for Breast Cancer based on MII specifications"
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2025+
releaseLabel: ci-build

publisher:
  name: BIH CEI
  url: http://example.org/example-publisher

dependencies:
  de.medizininformatikinitiative.kerndatensatz.onkologie: 2026.0.0
  de.medizininformatikinitiative.kerndatensatz.patho: 2026.0.0
  de.medizininformatikinitiative.kerndatensatz.base: 2026.0.0
  de.medizininformatikinitiative.kerndatensatz.biobank: 2026.0.0

pages:
  index.md:
    title: Breast Cancer Specification
  clinical-context.md:
    title: Clinical Context
  motivation.md:
    title: Motivation
  biopsy-specimens.md:
    title: Core Needle Biopsy — Specimens
  resection-specimens.md:
    title: Breast Resection — Specimens
  document-viewer.xml:
    title: Befund-Viewer

menu:
  Home: index.html
  Clinical Context: clinical-context.html
  Motivation: motivation.html
  Stanzbiopsie:
    Specimens: biopsy-specimens.html
    ServiceRequest: ServiceRequest-CoreNeedleBiopsyReportRequest.html
    MacroscopyGrouper: Observation-CoreNeedleBiopsyMacroscopicGrouper.html
    DiagnosticConclusionGrouper: Observation-CoreNeedleBiopsyDiagnosticConclusionGrouper.html
    DiagnosticReport: DiagnosticReport-CoreNeedleBiopsyReport.html
    Composition: Composition-CoreNeedleBiopsyComposition.html
  OP-Präparat (BET):
    Specimens: resection-specimens.html
    ServiceRequest: ServiceRequest-BreastResectionReportRequest.html
    MacroscopyGrouper: Observation-BreastResectionMacroscopicGrouper.html
    DiagnosticConclusionGrouper: Observation-BreastResectionDiagnosticConclusionGrouper.html
    DiagnosticReport: DiagnosticReport-BreastResectionReport.html
    Composition: Composition-BreastResectionComposition.html
  Befund-Viewer: document-viewer.html
  Artifacts: artifacts.html

instanceOptions:
  manualSliceOrdering: true
